import HeartIcon from "assets/icons/ic_heart_fill.svg";

export const categoryListData = [
  {
    icon: {
      src: HeartIcon,
      alt: "test",
    },
    subCategories: [
      { title: "Tất cả", slug: "all" },
      { title: "Đồ chơi công nghệ 1", slug: "do-choi-cong-nghe-1" },
      { title: "Đồ chơi công nghệ 2", slug: "do-choi-cong-nghe-2" },
      { title: "Đồ chơi công nghệ 3", slug: "do-choi-cong-nghe-3" },
      { title: "Đồ chơi công nghệ 4", slug: "do-choi-cong-nghe-4" },
      { title: "Đồ chơi công nghệ 5", slug: "do-choi-cong-nghe-5" },
      { title: "Đồ chơi công nghệ 6", slug: "do-choi-cong-nghe-6" },
    ],
    title: "Tất cả",
    description: "",
    slug: "",
    thumbnail: [
      "https://source.unsplash.com/random",
      "https://source.unsplash.com/random",
      "https://source.unsplash.com/random",
      "https://source.unsplash.com/random",
      "https://source.unsplash.com/random",
    ],
  },
  {
    icon: {
      src: HeartIcon,
      alt: "test",
    },
    subCategories: [
      { title: "Tất cả", slug: "all" },
      { title: "Đồ chơi công nghệ 1", slug: "do-choi-cong-nghe-1" },
      { title: "Đồ chơi công nghệ 2", slug: "do-choi-cong-nghe-2" },
      { title: "Đồ chơi công nghệ 3", slug: "do-choi-cong-nghe-3" },
      { title: "Đồ chơi công nghệ 4", slug: "do-choi-cong-nghe-4" },
      { title: "Đồ chơi công nghệ 5", slug: "do-choi-cong-nghe-5" },
      { title: "Đồ chơi công nghệ 6", slug: "do-choi-cong-nghe-6" },
    ],
    title: "Điện thoại",
    description:
      "Smart phone is a mobile phone which offers advanced technologies with functionality similar as a personal computer",
    slug: "smartphones",
    thumbnail: [
      "https://source.unsplash.com/random",
      "https://source.unsplash.com/random",
      "https://source.unsplash.com/random",
      "https://source.unsplash.com/random",
      "https://source.unsplash.com/random",
    ],
  },
  {
    icon: {
      src: HeartIcon,
      alt: "test",
    },
    subCategories: [
      { title: "Tất cả", slug: "all" },
      { title: "Đồ chơi công nghệ 1", slug: "do-choi-cong-nghe-1" },
      { title: "Đồ chơi công nghệ 2", slug: "do-choi-cong-nghe-2" },
      { title: "Đồ chơi công nghệ 3", slug: "do-choi-cong-nghe-3" },
      { title: "Đồ chơi công nghệ 4", slug: "do-choi-cong-nghe-4" },
      { title: "Đồ chơi công nghệ 5", slug: "do-choi-cong-nghe-5" },
      { title: "Đồ chơi công nghệ 6", slug: "do-choi-cong-nghe-6" },
    ],
    title: "Laptop",
    description:
      "A laptop, laptop computer, or notebook computer is a small, portable personal computer (PC) with a screen and alphanumeric keyboard.",
    slug: "laptops",
    thumbnail: [
      "https://source.unsplash.com/random",
      "https://source.unsplash.com/random",
      "https://source.unsplash.com/random",
      "https://source.unsplash.com/random",
      "https://source.unsplash.com/random",
    ],
  },
  {
    icon: {
      src: HeartIcon,
      alt: "test",
    },
    subCategories: [
      { title: "Tất cả", slug: "all" },
      { title: "Đồ chơi công nghệ 1", slug: "do-choi-cong-nghe-1" },
      { title: "Đồ chơi công nghệ 2", slug: "do-choi-cong-nghe-2" },
      { title: "Đồ chơi công nghệ 3", slug: "do-choi-cong-nghe-3" },
      { title: "Đồ chơi công nghệ 4", slug: "do-choi-cong-nghe-4" },
      { title: "Đồ chơi công nghệ 5", slug: "do-choi-cong-nghe-5" },
      { title: "Đồ chơi công nghệ 6", slug: "do-choi-cong-nghe-6" },
    ],
    title: "Nước hoa",
    description:
      "Fragrances are very complex products that go through many stages of development before reaching the consumer.",
    slug: "fragrances",
    thumbnail: [
      "https://source.unsplash.com/random",
      "https://source.unsplash.com/random",
      "https://source.unsplash.com/random",
      "https://source.unsplash.com/random",
      "https://source.unsplash.com/random",
    ],
  },
  {
    icon: {
      src: HeartIcon,
      alt: "test",
    },
    subCategories: [
      { title: "Tất cả", slug: "all" },
      { title: "Đồ chơi công nghệ 1", slug: "do-choi-cong-nghe-1" },
      { title: "Đồ chơi công nghệ 2", slug: "do-choi-cong-nghe-2" },
      { title: "Đồ chơi công nghệ 3", slug: "do-choi-cong-nghe-3" },
      { title: "Đồ chơi công nghệ 4", slug: "do-choi-cong-nghe-4" },
      { title: "Đồ chơi công nghệ 5", slug: "do-choi-cong-nghe-5" },
      { title: "Đồ chơi công nghệ 6", slug: "do-choi-cong-nghe-6" },
    ],
    title: "Skincare",
    description: "",
    slug: "skincare",
    thumbnail: [
      "https://source.unsplash.com/random",
      "https://source.unsplash.com/random",
      "https://source.unsplash.com/random",
      "https://source.unsplash.com/random",
      "https://source.unsplash.com/random",
    ],
  },
  {
    icon: {
      src: HeartIcon,
      alt: "test",
    },
    subCategories: [
      { title: "Tất cả", slug: "all" },
      { title: "Đồ chơi công nghệ 1", slug: "do-choi-cong-nghe-1" },
      { title: "Đồ chơi công nghệ 2", slug: "do-choi-cong-nghe-2" },
      { title: "Đồ chơi công nghệ 3", slug: "do-choi-cong-nghe-3" },
      { title: "Đồ chơi công nghệ 4", slug: "do-choi-cong-nghe-4" },
      { title: "Đồ chơi công nghệ 5", slug: "do-choi-cong-nghe-5" },
      { title: "Đồ chơi công nghệ 6", slug: "do-choi-cong-nghe-6" },
    ],
    title: "Tạp hóa",
    description: "",
    slug: "groceries",
    thumbnail: [
      "https://source.unsplash.com/random",
      "https://source.unsplash.com/random",
      "https://source.unsplash.com/random",
      "https://source.unsplash.com/random",
      "https://source.unsplash.com/random",
    ],
  },
  {
    icon: {
      src: HeartIcon,
      alt: "test",
    },
    subCategories: [
      { title: "Tất cả", slug: "all" },
      { title: "Đồ chơi công nghệ 1", slug: "do-choi-cong-nghe-1" },
      { title: "Đồ chơi công nghệ 2", slug: "do-choi-cong-nghe-2" },
      { title: "Đồ chơi công nghệ 3", slug: "do-choi-cong-nghe-3" },
      { title: "Đồ chơi công nghệ 4", slug: "do-choi-cong-nghe-4" },
      { title: "Đồ chơi công nghệ 5", slug: "do-choi-cong-nghe-5" },
      { title: "Đồ chơi công nghệ 6", slug: "do-choi-cong-nghe-6" },
    ],
    title: "Trang trí nhà cửa",
    description: "",
    slug: "home-decoration",
    thumbnail: [
      "https://source.unsplash.com/random",
      "https://source.unsplash.com/random",
      "https://source.unsplash.com/random",
      "https://source.unsplash.com/random",
      "https://source.unsplash.com/random",
    ],
  },
  {
    icon: {
      src: HeartIcon,
      alt: "test",
    },
    subCategories: [],
    title: "Đồ nội thất",
    description: "",
    slug: "furniture",
    thumbnail: [
      "https://source.unsplash.com/random",
      "https://source.unsplash.com/random",
      "https://source.unsplash.com/random",
      "https://source.unsplash.com/random",
      "https://source.unsplash.com/random",
    ],
  },
  {
    icon: {
      src: HeartIcon,
      alt: "test",
    },
    subCategories: [
      { title: "Tất cả", slug: "all" },
      { title: "Đồ chơi công nghệ 1", slug: "do-choi-cong-nghe-1" },
      { title: "Đồ chơi công nghệ 2", slug: "do-choi-cong-nghe-2" },
      { title: "Đồ chơi công nghệ 3", slug: "do-choi-cong-nghe-3" },
      { title: "Đồ chơi công nghệ 4", slug: "do-choi-cong-nghe-4" },
      { title: "Đồ chơi công nghệ 5", slug: "do-choi-cong-nghe-5" },
      { title: "Đồ chơi công nghệ 6", slug: "do-choi-cong-nghe-6" },
    ],
    title: "Top",
    description: "",
    slug: "tops",
    thumbnail: [
      "https://source.unsplash.com/random",
      "https://source.unsplash.com/random",
      "https://source.unsplash.com/random",
      "https://source.unsplash.com/random",
      "https://source.unsplash.com/random",
    ],
  },
  {
    icon: {
      src: HeartIcon,
      alt: "test",
    },
    subCategories: [],
    title: "Váy/Đầm",
    description: "",
    slug: "womens-dresses",
    thumbnail: [],
  },
  {
    icon: {
      src: HeartIcon,
      alt: "test",
    },
    subCategories: [],
    title: "Giày nữ",
    description: "",
    slug: "womens-shoes",
    thumbnail: [],
  },
  {
    icon: {
      src: HeartIcon,
      alt: "test",
    },
    subCategories: [],
    title: "Túi xách nữ",
    description: "",
    slug: "womens-bags",
    thumbnail: [],
  },
  {
    icon: {
      src: HeartIcon,
      alt: "test",
    },
    subCategories: [],
    title: "Trang sức",
    description: "",
    slug: "womens-jewellery",
    thumbnail: [
      "https://source.unsplash.com/random",
      "https://source.unsplash.com/random",
      "https://source.unsplash.com/random",
      "https://source.unsplash.com/random",
      "https://source.unsplash.com/random",
    ],
  },
  {
    icon: {
      src: HeartIcon,
      alt: "test",
    },
    subCategories: [],
    title: "Đồng hồ nữ",
    description: "",
    slug: "womens-watches",
    thumbnail: [
      "https://source.unsplash.com/random",
      "https://source.unsplash.com/random",
      "https://source.unsplash.com/random",
      "https://source.unsplash.com/random",
      "https://source.unsplash.com/random",
    ],
  },
  {
    icon: {
      src: HeartIcon,
      alt: "test",
    },
    subCategories: [],
    title: "Nước hoa nam",
    description: "",
    slug: "mens-shirts",
    thumbnail: [
      "https://source.unsplash.com/random",
      "https://source.unsplash.com/random",
      "https://source.unsplash.com/random",
      "https://source.unsplash.com/random",
      "https://source.unsplash.com/random",
    ],
  },
  {
    icon: {
      src: HeartIcon,
      alt: "test",
    },
    subCategories: [
      { title: "Tất cả", slug: "all" },
      { title: "Đồ chơi công nghệ 1", slug: "do-choi-cong-nghe-1" },
      { title: "Đồ chơi công nghệ 2", slug: "do-choi-cong-nghe-2" },
      { title: "Đồ chơi công nghệ 3", slug: "do-choi-cong-nghe-3" },
      { title: "Đồ chơi công nghệ 4", slug: "do-choi-cong-nghe-4" },
      { title: "Đồ chơi công nghệ 5", slug: "do-choi-cong-nghe-5" },
      { title: "Đồ chơi công nghệ 6", slug: "do-choi-cong-nghe-6" },
    ],
    title: "Giày nam",
    description: "",
    slug: "mens-shoes",
    thumbnail: [
      "https://source.unsplash.com/random",
      "https://source.unsplash.com/random",
      "https://source.unsplash.com/random",
      "https://source.unsplash.com/random",
      "https://source.unsplash.com/random",
    ],
  },
  {
    icon: {
      src: HeartIcon,
      alt: "test",
    },
    subCategories: [
      { title: "Tất cả", slug: "all" },
      { title: "Đồ chơi công nghệ 1", slug: "do-choi-cong-nghe-1" },
      { title: "Đồ chơi công nghệ 2", slug: "do-choi-cong-nghe-2" },
      { title: "Đồ chơi công nghệ 3", slug: "do-choi-cong-nghe-3" },
      { title: "Đồ chơi công nghệ 4", slug: "do-choi-cong-nghe-4" },
      { title: "Đồ chơi công nghệ 5", slug: "do-choi-cong-nghe-5" },
      { title: "Đồ chơi công nghệ 6", slug: "do-choi-cong-nghe-6" },
    ],
    title: "Đồng hồ nam",
    description: "",
    slug: "mens-watches",
    thumbnail: [
      "https://source.unsplash.com/random",
      "https://source.unsplash.com/random",
      "https://source.unsplash.com/random",
      "https://source.unsplash.com/random",
      "https://source.unsplash.com/random",
    ],
  },
  {
    icon: {
      src: HeartIcon,
      alt: "test",
    },
    subCategories: [
      { title: "Tất cả", slug: "all" },
      { title: "Đồ chơi công nghệ 1", slug: "do-choi-cong-nghe-1" },
      { title: "Đồ chơi công nghệ 2", slug: "do-choi-cong-nghe-2" },
      { title: "Đồ chơi công nghệ 3", slug: "do-choi-cong-nghe-3" },
      { title: "Đồ chơi công nghệ 4", slug: "do-choi-cong-nghe-4" },
      { title: "Đồ chơi công nghệ 5", slug: "do-choi-cong-nghe-5" },
      { title: "Đồ chơi công nghệ 6", slug: "do-choi-cong-nghe-6" },
    ],
    title: "Kính râm",
    description: "",
    slug: "sunglasses",
    thumbnail: [
      "https://source.unsplash.com/random",
      "https://source.unsplash.com/random",
      "https://source.unsplash.com/random",
      "https://source.unsplash.com/random",
      "https://source.unsplash.com/random",
    ],
  },
  {
    icon: {
      src: HeartIcon,
      alt: "test",
    },
    subCategories: [
      { title: "Tất cả", slug: "all" },
      { title: "Đồ chơi công nghệ 1", slug: "do-choi-cong-nghe-1" },
      { title: "Đồ chơi công nghệ 2", slug: "do-choi-cong-nghe-2" },
      { title: "Đồ chơi công nghệ 3", slug: "do-choi-cong-nghe-3" },
      { title: "Đồ chơi công nghệ 4", slug: "do-choi-cong-nghe-4" },
      { title: "Đồ chơi công nghệ 5", slug: "do-choi-cong-nghe-5" },
      { title: "Đồ chơi công nghệ 6", slug: "do-choi-cong-nghe-6" },
    ],
    title: "Ô tô",
    description: "",
    slug: "automotive",
    thumbnail: [
      "https://source.unsplash.com/random",
      "https://source.unsplash.com/random",
      "https://source.unsplash.com/random",
      "https://source.unsplash.com/random",
      "https://source.unsplash.com/random",
    ],
  },
  {
    icon: {
      src: HeartIcon,
      alt: "test",
    },
    subCategories: [
      { title: "Tất cả", slug: "all" },
      { title: "Đồ chơi công nghệ 1", slug: "do-choi-cong-nghe-1" },
      { title: "Đồ chơi công nghệ 2", slug: "do-choi-cong-nghe-2" },
      { title: "Đồ chơi công nghệ 3", slug: "do-choi-cong-nghe-3" },
      { title: "Đồ chơi công nghệ 4", slug: "do-choi-cong-nghe-4" },
      { title: "Đồ chơi công nghệ 5", slug: "do-choi-cong-nghe-5" },
      { title: "Đồ chơi công nghệ 6", slug: "do-choi-cong-nghe-6" },
    ],
    title: "Mô tô",
    description: "",
    slug: "motorcycle",
    thumbnail: [
      "https://source.unsplash.com/random",
      "https://source.unsplash.com/random",
      "https://source.unsplash.com/random",
      "https://source.unsplash.com/random",
      "https://source.unsplash.com/random",
    ],
  },
  {
    icon: {
      src: HeartIcon,
      alt: "test",
    },
    subCategories: [
      { title: "Tất cả", slug: "all" },
      { title: "Đồ chơi công nghệ 1", slug: "do-choi-cong-nghe-1" },
      { title: "Đồ chơi công nghệ 2", slug: "do-choi-cong-nghe-2" },
      { title: "Đồ chơi công nghệ 3", slug: "do-choi-cong-nghe-3" },
      { title: "Đồ chơi công nghệ 4", slug: "do-choi-cong-nghe-4" },
      { title: "Đồ chơi công nghệ 5", slug: "do-choi-cong-nghe-5" },
      { title: "Đồ chơi công nghệ 6", slug: "do-choi-cong-nghe-6" },
    ],
    title: "Bóng đèn",
    description: "",
    slug: "lighting",
    thumbnail: [
      "https://source.unsplash.com/random",
      "https://source.unsplash.com/random",
      "https://source.unsplash.com/random",
      "https://source.unsplash.com/random",
      "https://source.unsplash.com/random",
    ],
  },
];

export const shortByData = [
  { label: "Phổ biến", value: "popular" },
  { label: "Mới nhất", value: "latest" },
  { label: "Bán cháy", value: "best" },
];

export const shortByPriceData = [
  { id: 1, label: "Giá cao nhất", value: "max" },
  { id: 2, label: "Giá thấp nhất", value: "min" },
];

export const colorData = [
  {
    label: "Hồng",
    code: "#e7587b",
  },
  {
    label: "Đỏ",
    code: "#ff0045",
  },
  {
    label: "Trắng",
    code: "#fff",
  },
  {
    label: "Xanh đen",
    code: "#252425",
  },
  {
    label: "Xanh sky",
    code: "#127daf",
  },
  {
    label: "Xanh lá",
    code: "#127d11",
  },
  {
    label: "Xanh đen",
    code: "#191a21",
  },
];
export default undefined;
