export const CONSTANT_ROUTE = {
  EN: {
    HOME: "",
    PRODUCT_DETAIL: "product-detail",
    CART: "carts",
    CATEGORY: "categories",
    NEWS_DETAIL: "news-detail",
    ABOUT_US: "about-us",
    LOGIN: "login",
    REGISTER: "register",
    FORGOT_PASSWORD: "forgot-password",
    RESET_PASSWORD: "reset-password",
    VERIFY: "verify",
  },
  VI: {
    HOME: "",
    PRODUCT_DETAIL: "chi-tiet-san-pham",
    CART: "gio-hang",
    CATEGORY: "danh-muc",
    NEWS_DETAIL: "chi-tiet-tin-tuc",
    ABOUT_US: "ve-chung-toi",
    LOGIN: "dang-nhap",
    REGISTER: "dang-ky",
    FORGOT_PASSWORD: "quen-mat-khau",
    RESET_PASSWORD: "cap-nhap-mat-khau",
    VERIFY: "ma-hoa",
  },
};
